### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by fran-pena** [jprichardson/d3-measure-text#3]
Hi,

I am downloaded _d3-measure-text.js_ and included  `<script src="./d3-measure-text.js"></script>` in the head section. When I put in my JS code the line `var d3MeasureText = require('d3-measure-text');` you suggest, the following error appears:

> ReferenceError: require is not defined
> var d3MeasureText = require('d3-measure-text');

Best, Fran

**Comment by jprichardson** [comment]
You don't use `require` if you use the `<script>` tag. So call `window.d3MeasureText` instead.
